apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mzgxgy688-nodejs
  janus-idp.io/tekton: mzgxgy688-nodejs
  backstage.io/kubernetes-id: mzgxgy688-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mzgxgy688-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
